import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "./store";
import { baseAxios } from "../utils/axios";
import { Account, Order, OrderResponse } from "../types/order";
import axios from "axios";
import { API_URL } from "../constants";
import { accountApi, AccountResponse } from "../utils/api/accountApi";

export interface AccountState extends Omit<Account, "id"> {
  id: string | null;
  status: "idle" | "loading" | "failed";
}

const initialState: AccountState = {
  id: null,
  balance: "0",
  closedOrders: [],
  openOrders: [],
  status: "idle",
};

export const removeOrder = createAsyncThunk(
  "account/removeOrder",
  async (orderId: string) => {
    try {
      const response = await baseAxios.delete(
        `/order/${orderId}?ticker=BTCUSDT.P`
      );
      return response.data;
    } catch (error) {
      throw error;
    }
  }
);

// dispatch(getAccount())
export const getAccount = createAsyncThunk("account/getAccount", async () => {
  const response = await baseAxios("/accounts/current");
  return response.data;
});

export const accountSlice = createSlice({
  name: "account",
  initialState,
  reducers: {
    clear: (state) => {
      state = initialState;
    },
    update: (state, action) => {
      state.id = action.payload.id;
      state.balance = action.payload.balance;
      state.openOrders = action.payload.open_orders || [];
      state.closedOrders = action.payload.closed_orders || [];
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addMatcher(accountApi.endpoints.getAccount.matchPending, (state) => {
        state.status = "loading";
      })
      .addMatcher(
        accountApi.endpoints.getAccount.matchFulfilled,
        (state, { payload }: PayloadAction<AccountResponse>) => {
          return {
            ...state,
            status: "idle",
            ...payload.account,
          };
        }
      );
  },
});

export const { clear, update } = accountSlice.actions;
export const account = (state: RootState) => state.account;
export default accountSlice.reducer;
