import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "./store";
import { orderBookApi } from "../utils/api/orderBookApi";
import { OrderWithDepth } from "../types/orderBook";
import {
  asksToState,
  getPercentage,
  getSpread,
  orderToState,
} from "../sections/orderbook/helpers";

export interface OrderBookState {
  bids: OrderWithDepth[];
  asks: OrderWithDepth[];
  bids_size: number;
  asks_size: number;
  spread: number;
  percentage: number;
  status: "idle" | "loading" | "failed";
}

const initialState: OrderBookState = {
  bids: [],
  asks: [],
  asks_size: 0,
  bids_size: 0,
  status: "idle",
  spread: 0,
  percentage: 0,
};

export const orderBookSlice = createSlice({
  name: "orderbook",
  initialState,
  reducers: {
    clear: state => {
      state.bids = [];
      state.asks = [];
    },
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
    builder
      .addMatcher(orderBookApi.endpoints.getOrderBook.matchPending, state => {
        state.status = "loading";
      })
      .addMatcher(
        orderBookApi.endpoints.getOrderBook.matchFulfilled,
        (state, { payload }) => {
          state.status = "idle";
          const bids = orderToState(payload.bids);
          const asks = asksToState(payload.asks);
          const bids_size = payload.bidsSize;
          const asks_size = payload.asksSize;

          state.bids = bids;
          state.asks = asks;
          state.bids_size = bids_size;
          state.asks_size = asks_size;
          const spread = getSpread(bids, asks);
          state.spread = spread;
          state.percentage = getPercentage(bids, asks, spread);
        }
      )
      .addMatcher(orderBookApi.endpoints.getOrderBook.matchRejected, state => {
        state.status = "failed";
      });
  },
});

export const { clear } = orderBookSlice.actions;
export const orderBook = (state: RootState) => state.orderBook;
export default orderBookSlice.reducer;
