on: [pull_request]
name: Continuous Integration
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Build
        run: make build
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn
    - name: Check code
      run: yarn type-check
    - name: Lint
      run: yarn lint
      continue-on-error: true
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn
    - name: Test
      run: yarn test
      continue-on-error: true

