name: Apply Helm Charts to EKS Cluster

on:
  workflow_run:
    workflows:
      - "Build and Push Multi-Arch Docker Image"
    types:
      - completed
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  deploy-devnet:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      id-token: write
      contents: read
    name: Deploy to devnet
    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4
    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0
    - name: Uses Twingate GitHub Action
      uses: twingate/github-action@v1
      with:
        # Required
        service-key: ${{ secrets.TWINGATE_KEY }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_EKS }}
        aws-region: ${{ secrets.AWS_REGION_EKS }}
        role-session-name: "${{ github.run_id }}-${{ github.run_attempt }}"
        role-duration-seconds: 1200
    - name: Get kubeconfig
      run: aws eks update-kubeconfig --name dev-sphx-eu-west-2 --region ${{ secrets.AWS_REGION_EKS }}
    - name: Test cluster access
      run: kubectl get all
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Declare some variables
      id: set_vars
      shell: bash
      run: |
        echo "COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Deploy Helm chart
      run: |
        helm package --app-version=$BRANCH-$COMMIT_SHA_SHORT helm/lynxweb
        helm upgrade --install lynxweb -f ./helm/lynxweb/values.dev.yaml \
         ./lynxweb-0.1.0.tgz --set lynxweb.tag=$BRANCH-$COMMIT_SHA_SHORT --namespace dev

  deploy-testnet:
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v')
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      id-token: write
      contents: read
    name: Deploy to testnet
    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4
    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0
    - name: Uses Twingate GitHub Action
      uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_KEY }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_EKS }}
        aws-region: ${{ secrets.AWS_REGION_EKS }}
        role-session-name: "${{ github.run_id }}-${{ github.run_attempt }}"
        role-duration-seconds: 1200
    - name: Get kubeconfig
      run: aws eks update-kubeconfig --name testnet-sphx-eu-west-2 --region ${{ secrets.AWS_REGION_EKS }}
    - name: Test cluster access
      run: kubectl get all
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Declare some variables
      id: set_vars
      shell: bash
      run: |
        echo "COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Deploy Helm chart
      run: |
        helm package --app-version=$TAG-$COMMIT_SHA_SHORT helm/lynxweb
        helm upgrade --install lynxweb -f ./helm/lynxweb/values.testnet.yaml \
         ./lynxweb-0.1.0.tgz --set lynxweb.tag=$TAG-$COMMIT_SHA_SHORT --namespace testnet
    
  