name: Build
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: arc-runner-set
    container:
      image: buildpack-deps:jammy
    timeout-minutes: 15
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.7
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        run: make install && make lint
      - name: Test
        run: make install && make test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}