name: Debug Yarn Workflow

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
        type: boolean

jobs:
  debug-yarn:
    runs-on: arc-runner-set
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Check Yarn version
      run: yarn --version

    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Yarn version: $(yarn --version)"
        echo "PATH: $PATH"
        ls -la

    - name: Install dependencies
      run: yarn install --verbose

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Run a test command
      run: yarn run test
